BEGIN;

-- 2026-06-27 round 3 title review import.
-- Source: /Users/nicole/Downloads/jobpush_title_review_2026-06-27_500 (1).csv
-- Nicole marked 500 unresolved normalized titles as target/non-target.

CREATE TEMP TABLE manual_title_labels_20260627_round3 (
    normalized_title TEXT PRIMARY KEY,
    classification_status TEXT NOT NULL CHECK (classification_status IN ('target', 'non_target')),
    canonical_role TEXT,
    note TEXT
) ON COMMIT DROP;

INSERT INTO manual_title_labels_20260627_round3 (
    normalized_title, classification_status, canonical_role, note
) VALUES
    ('office manager', 'non_target', NULL, NULL),
    ('analytics engineer', 'target', NULL, NULL),
    ('field marketing manager', 'non_target', NULL, NULL),
    ('product operations manager', 'target', NULL, NULL),
    ('supply chain manager', 'target', NULL, NULL),
    ('engineer', 'target', NULL, NULL),
    ('safety engineer', 'target', NULL, NULL),
    ('customer service specialist', 'target', NULL, NULL),
    ('operations specialist', 'target', NULL, NULL),
    ('plant manager', 'non_target', NULL, NULL),
    ('senior growth marketing manager', 'non_target', NULL, NULL),
    ('site manager', 'target', NULL, NULL),
    ('facility engineer', 'non_target', NULL, NULL),
    ('sales operations analyst', 'target', NULL, NULL),
    ('associate engineer', 'target', NULL, NULL),
    ('operator', 'non_target', NULL, NULL),
    ('material handler 1', 'non_target', NULL, NULL),
    ('sr. quality engineer', 'non_target', NULL, NULL),
    ('sr. supplier quality engineer', 'non_target', NULL, NULL),
    ('community health worker', 'non_target', NULL, NULL),
    ('data operations analyst', 'target', NULL, NULL),
    ('environmental driver specialist cdlb', 'non_target', NULL, NULL),
    ('major account manager', 'non_target', NULL, NULL),
    ('material program manager', 'non_target', NULL, NULL),
    ('sr. inside sales business development manager', 'non_target', NULL, NULL),
    ('sr. territory manager eyecare', 'non_target', NULL, NULL),
    ('store management', 'non_target', NULL, NULL),
    ('client success manager', 'target', NULL, NULL),
    ('finance manager', 'non_target', NULL, NULL),
    ('quality manager', 'non_target', NULL, NULL),
    ('sales enablement manager', 'target', NULL, NULL),
    ('ios developer', 'target', NULL, NULL),
    ('manager data engineering', 'non_target', NULL, NULL),
    ('senior java developer', 'non_target', NULL, NULL),
    ('sr. project manager', 'non_target', NULL, NULL),
    ('android developer', 'target', NULL, NULL),
    ('senior automation engineer', 'non_target', NULL, NULL),
    ('senior executive assistant', 'non_target', NULL, NULL),
    ('senior project engineer', 'non_target', NULL, NULL),
    ('senior reliability engineer', 'non_target', NULL, NULL),
    ('project coordinator', 'target', NULL, NULL),
    ('medical science liaison', 'non_target', NULL, NULL),
    ('salesforce technical architect', 'target', NULL, NULL),
    ('sharepoint developer', 'non_target', NULL, NULL),
    ('analista de desenvolvimento de software pleno', 'non_target', NULL, NULL),
    ('analista de desenvolvimento de software sênior', 'non_target', NULL, NULL),
    ('associate analyst', 'target', NULL, NULL),
    ('customer service technical support rep', 'target', NULL, NULL),
    ('engineer senior', 'non_target', NULL, NULL),
    ('especialista de desenvolvimento de software i', 'non_target', NULL, NULL),
    ('senior cloud support engineer', 'non_target', NULL, NULL),
    ('administrative assistant pct', 'non_target', NULL, NULL),
    ('associate engineer tech support', 'target', NULL, NULL),
    ('cdl b driver', 'non_target', NULL, NULL),
    ('customer service self storage manager', 'non_target', NULL, NULL),
    ('dialysis technician', 'non_target', NULL, NULL),
    ('erp presales architect indirect channel w/m/d microsoft dynamics 365', 'target', NULL, NULL),
    ('machiniste cnc', 'non_target', NULL, NULL),
    ('medical technologist', 'non_target', NULL, NULL),
    ('monteur', 'non_target', NULL, NULL),
    ('packaging operator iii', 'non_target', NULL, NULL),
    ('pst specialist', 'non_target', NULL, NULL),
    ('senior power platform engineer w/m/x - schwerpunkt power pages', 'non_target', NULL, NULL),
    ('shift supervisor - overnight', 'non_target', NULL, NULL),
    ('sr. field performance technician', 'non_target', NULL, NULL),
    ('account development representative', 'non_target', NULL, NULL),
    ('assistant controller', 'non_target', NULL, NULL),
    ('inside sales specialist', 'non_target', NULL, NULL),
    ('marketing manager', 'target', NULL, NULL),
    ('senior engineering manager', 'target', NULL, NULL),
    ('senior technical program manager', 'target', NULL, NULL),
    ('technical architect', 'target', NULL, NULL),
    ('treasury analyst', 'non_target', NULL, NULL),
    ('maintenance planner', 'non_target', NULL, NULL),
    ('office coordinator', 'non_target', NULL, NULL),
    ('quality engineer ii', 'non_target', NULL, NULL),
    ('senior finance analyst', 'target', NULL, NULL),
    ('senior technical writer', 'target', NULL, NULL),
    ('ux designer', 'target', NULL, NULL),
    ('associate account manager', 'non_target', NULL, NULL),
    ('pricing analyst', 'non_target', NULL, NULL),
    ('servicenow developer', 'target', NULL, NULL),
    ('tax analyst', 'non_target', NULL, NULL),
    ('eletricista i', 'non_target', NULL, NULL),
    ('inventory specialist', 'non_target', NULL, NULL),
    ('manager business analytics', 'target', NULL, NULL),
    ('senior contract manager', 'non_target', NULL, NULL),
    ('senior industrial engineer', 'non_target', NULL, NULL),
    ('territory account manager', 'non_target', NULL, NULL),
    ('client executive', 'non_target', NULL, NULL),
    ('development manager', 'target', NULL, NULL),
    ('quality control inspector', 'non_target', NULL, NULL),
    ('teller', 'non_target', NULL, NULL),
    ('associate granite', 'non_target', NULL, NULL),
    ('courier i', 'non_target', NULL, NULL),
    ('experienced commissioning agent mission critical data centers', 'non_target', NULL, NULL),
    ('foreign trade zone administration manager hybrid', 'non_target', NULL, NULL),
    ('histotechnologist', 'non_target', NULL, NULL),
    ('medical lab technologist', 'non_target', NULL, NULL),
    ('network technician', 'non_target', NULL, NULL),
    ('order selector- 1st shift', 'non_target', NULL, NULL),
    ('order selector- 2nd shift', 'non_target', NULL, NULL),
    ('outreach executive i', 'non_target', NULL, NULL),
    ('phlebotomy site coordinator', 'non_target', NULL, NULL),
    ('quantitative trader', 'non_target', NULL, NULL),
    ('senior it-security berater in w/m/x', 'target', NULL, NULL),
    ('applications engineer', 'target', NULL, NULL),
    ('business development executive', 'target', NULL, NULL),
    ('customer support specialist', 'target', NULL, NULL),
    ('data science manager', 'target', NULL, NULL),
    ('fp a manager', 'non_target', NULL, NULL),
    ('general application', 'non_target', NULL, NULL),
    ('ios engineer', 'target', NULL, NULL),
    ('manager customer support', 'target', NULL, NULL),
    ('performance marketing manager', 'target', NULL, NULL),
    ('quality assurance engineer', 'target', NULL, NULL),
    ('sales coordinator', 'target', NULL, NULL),
    ('senior data platform engineer', 'target', NULL, NULL),
    ('senior .net developer', 'non_target', NULL, NULL),
    ('senior sales manager', 'non_target', NULL, NULL),
    ('senior software development engineer in test', 'non_target', NULL, NULL),
    ('senior supplier quality engineer', 'non_target', NULL, NULL),
    ('field application engineer', 'non_target', NULL, NULL),
    ('hrbp', 'non_target', NULL, NULL),
    ('hr coordinator', 'non_target', NULL, NULL),
    ('manager fp a', 'non_target', NULL, NULL),
    ('receiving coordinator', 'non_target', NULL, NULL),
    ('sales account manager', 'non_target', NULL, NULL),
    ('senior applications engineer', 'non_target', NULL, NULL),
    ('senior designer', 'non_target', NULL, NULL),
    ('site reliability engineer ii', 'non_target', NULL, NULL),
    ('strategic finance manager', 'non_target', NULL, NULL),
    ('c++ developer', 'non_target', NULL, NULL),
    ('platform engineer', 'non_target', NULL, NULL),
    ('qa analyst', 'target', NULL, NULL),
    ('senior salesforce developer', 'non_target', NULL, NULL),
    ('technical trainer', 'non_target', NULL, NULL),
    ('workplace coordinator', 'non_target', NULL, NULL),
    ('forklift operator', 'non_target', NULL, NULL),
    ('painter', 'non_target', NULL, NULL),
    ('project engineer ii', 'non_target', NULL, NULL),
    ('security officer l1', 'non_target', NULL, NULL),
    ('transportation supervisor', 'non_target', NULL, NULL),
    ('wiring technician', 'non_target', NULL, NULL),
    ('actuarial analyst iii', 'non_target', NULL, NULL),
    ('analista de dados sênior', 'non_target', NULL, NULL),
    ('asset protection manager', 'non_target', NULL, NULL),
    ('assistant manager - sales', 'target', NULL, NULL),
    ('associate buying operations', 'non_target', NULL, NULL),
    ('brand steward', 'non_target', NULL, NULL),
    ('client services executive - hybrid', 'non_target', NULL, NULL),
    ('delivery associate', 'non_target', NULL, NULL),
    ('engineer iii', 'non_target', NULL, NULL),
    ('executivo comercial v', 'non_target', NULL, NULL),
    ('group underwriter senior', 'non_target', NULL, NULL),
    ('ie layout engineer', 'non_target', NULL, NULL),
    ('product and pipeline communications manager', 'target', NULL, NULL),
    ('senior implementation engineer', 'non_target', NULL, NULL),
    ('senior system administrator', 'non_target', NULL, NULL),
    ('specialized operations associate', 'non_target', NULL, NULL),
    ('sr engineer data smai', 'non_target', NULL, NULL),
    ('sr engineer it ai enablement', 'non_target', NULL, NULL),
    ('sr. supply manager at supply management- capital', 'non_target', NULL, NULL),
    ('supervisor material planning', 'non_target', NULL, NULL),
    ('taiwan fab equip maintenance engineer', 'non_target', NULL, NULL),
    ('technologist', 'non_target', NULL, NULL),
    ('tokarz nc m/k/n', 'non_target', NULL, NULL),
    ('ui developer', 'target', NULL, NULL),
    ('wiring technician - 3rd shift', 'non_target', NULL, NULL),
    ('account manager sme growth', 'non_target', NULL, NULL),
    ('business development manager energy', 'target', NULL, NULL),
    ('concrete repair laborer', 'non_target', NULL, NULL),
    ('customer relationship specialist granite', 'non_target', NULL, NULL),
    ('deployment strategist build to apply - us government', 'target', NULL, NULL),
    ('dialysis technician pct', 'non_target', NULL, NULL),
    ('emt-basic - radford transport - ft', 'non_target', NULL, NULL),
    ('emt-basic - roanoke transport - ft', 'non_target', NULL, NULL),
    ('equipment operator- 2nd shift', 'non_target', NULL, NULL),
    ('hospital services administrator', 'non_target', NULL, NULL),
    ('inside sales rep-hourly + commission-can live anywhere in u.s.', 'non_target', NULL, NULL),
    ('light equipment operator 1', 'non_target', NULL, NULL),
    ('macariqueiro i', 'non_target', NULL, NULL),
    ('manager ii study management associate sma', 'non_target', NULL, NULL),
    ('manager scrum master', 'non_target', NULL, NULL),
    ('medical support assistant msa - veterans affairs clinic', 'non_target', NULL, NULL),
    ('onsite lab support clerk', 'non_target', NULL, NULL),
    ('practice manager', 'non_target', NULL, NULL),
    ('program planner ii - onsite', 'non_target', NULL, NULL),
    ('rn facility administrator', 'non_target', NULL, NULL),
    ('senior client success manager - programmatic', 'non_target', NULL, NULL),
    ('senior market controller alpine m/w/d', 'non_target', NULL, NULL),
    ('senior superintendent water/wastewater', 'non_target', NULL, NULL),
    ('software development engineer iii', 'target', NULL, NULL),
    ('sr anlyst procurement', 'non_target', NULL, NULL),
    ('sr. program planner i - onsite', 'non_target', NULL, NULL),
    ('telepharmacy technician', 'non_target', NULL, NULL),
    ('advanced engineer', 'non_target', NULL, NULL),
    ('client relationship manager', 'non_target', NULL, NULL),
    ('content marketing manager', 'non_target', NULL, NULL),
    ('cost analyst', 'non_target', NULL, NULL),
    ('demand generation manager', 'non_target', NULL, NULL),
    ('ehs manager', 'non_target', NULL, NULL),
    ('finance intern', 'non_target', NULL, NULL),
    ('inside sales rep', 'non_target', NULL, NULL),
    ('logistics coordinator', 'non_target', NULL, NULL),
    ('maintenance manager', 'non_target', NULL, NULL),
    ('marketing coordinator', 'target', NULL, NULL),
    ('procurement specialist', 'non_target', NULL, NULL),
    ('resident engineer', 'non_target', NULL, NULL),
    ('sales operations manager', 'target', NULL, NULL),
    ('senior controls engineer', 'non_target', NULL, NULL),
    ('senior design quality engineer', 'non_target', NULL, NULL),
    ('senior it engineer', 'non_target', NULL, NULL),
    ('senior manager engineering', 'non_target', NULL, NULL),
    ('senior technical analyst', 'target', NULL, NULL),
    ('service engineer', 'target', NULL, NULL),
    ('social media manager', 'target', NULL, NULL),
    ('territory manager', 'non_target', NULL, NULL),
    ('administrative coordinator', 'non_target', NULL, NULL),
    ('ai automation engineer', 'target', NULL, NULL),
    ('electronics technician', 'non_target', NULL, NULL),
    ('events manager', 'non_target', NULL, NULL),
    ('facilities technician', 'non_target', NULL, NULL),
    ('field applications engineer', 'non_target', NULL, NULL),
    ('fpga engineer', 'non_target', NULL, NULL),
    ('hr analyst', 'non_target', NULL, NULL),
    ('maintenance supervisor', 'non_target', NULL, NULL),
    ('manager engineering', 'non_target', NULL, NULL),
    ('manager sales development', 'non_target', NULL, NULL),
    ('marketing operations manager', 'non_target', NULL, NULL),
    ('network analyst', 'target', NULL, NULL),
    ('onboarding manager', 'non_target', NULL, NULL),
    ('procurement manager', 'non_target', NULL, NULL),
    ('project executive', 'non_target', NULL, NULL),
    ('reliability engineer', 'non_target', NULL, NULL),
    ('senior fpga engineer', 'non_target', NULL, NULL),
    ('senior manager finance', 'non_target', NULL, NULL),
    ('senior optical engineer', 'non_target', NULL, NULL),
    ('senior software quality engineer', 'non_target', NULL, NULL),
    ('senior systems administrator', 'non_target', NULL, NULL),
    ('senior tax analyst', 'non_target', NULL, NULL),
    ('sr. administrative assistant', 'non_target', NULL, NULL),
    ('sr. network engineer', 'non_target', NULL, NULL),
    ('support analyst', 'target', NULL, NULL),
    ('tibco developer', 'non_target', NULL, NULL),
    ('ai infrastructure engineer', 'target', NULL, NULL),
    ('application support analyst', 'target', NULL, NULL),
    ('auxiliar de produção', 'non_target', NULL, NULL),
    ('category manager', 'non_target', NULL, NULL),
    ('change coordinator', 'non_target', NULL, NULL),
    ('crm specialist', 'target', NULL, NULL),
    ('customer service advocate', 'non_target', NULL, NULL),
    ('equipment operator', 'non_target', NULL, NULL),
    ('general manager', 'non_target', NULL, NULL),
    ('laborer', 'non_target', NULL, NULL),
    ('mi product sales specialist', 'target', NULL, NULL),
    ('product marketing engineer', 'target', NULL, NULL),
    ('project engineering manager', 'target', NULL, NULL),
    ('salesforce project manager', 'target', NULL, NULL),
    ('senior product quality engineer', 'non_target', NULL, NULL),
    ('support engineer', 'target', NULL, NULL),
    ('support specialist', 'target', NULL, NULL),
    ('system administrator', 'target', NULL, NULL),
    ('assembly technician', 'non_target', NULL, NULL),
    ('athletic trainer', 'non_target', NULL, NULL),
    ('cdl a driver', 'non_target', NULL, NULL),
    ('commodity manager', 'non_target', NULL, NULL),
    ('document controller specialist', 'non_target', NULL, NULL),
    ('escrow assistant', 'non_target', NULL, NULL),
    ('heavy equipment operator', 'non_target', NULL, NULL),
    ('robot operator', 'non_target', NULL, NULL),
    ('software development engineer in test sdet', 'target', NULL, NULL),
    ('technical leader', 'non_target', NULL, NULL),
    ('agentic ai copilot studio / power-platform expert w/m/x', 'target', NULL, NULL),
    ('agent strategy manager', 'target', NULL, NULL),
    ('ai deployment engineer', 'target', NULL, NULL),
    ('analyst ii product technical support', 'target', NULL, NULL),
    ('analytics and reporting sr analytics ikc', 'target', NULL, NULL),
    ('assistant manager', 'non_target', NULL, NULL),
    ('bindery operator 1', 'non_target', NULL, NULL),
    ('client retention specialist remote', 'non_target', NULL, NULL),
    ('courier', 'non_target', NULL, NULL),
    ('database reliability engineer - core team', 'target', NULL, NULL),
    ('development coordinator', 'target', NULL, NULL),
    ('escrow officer', 'non_target', NULL, NULL),
    ('field service engineer 2 non exempt', 'non_target', NULL, NULL),
    ('financial systems administrator', 'non_target', NULL, NULL),
    ('group facility administrator', 'non_target', NULL, NULL),
    ('hoist operator 2', 'non_target', NULL, NULL),
    ('human resource specialist', 'non_target', NULL, NULL),
    ('inserter operator 3', 'non_target', NULL, NULL),
    ('inventory control coordinator', 'non_target', NULL, NULL),
    ('jr. a+ field it engineer', 'non_target', NULL, NULL),
    ('laboratory robotics operator', 'non_target', NULL, NULL),
    ('manager contracts onsite', 'non_target', NULL, NULL),
    ('manager field services', 'non_target', NULL, NULL),
    ('press operator 3', 'non_target', NULL, NULL),
    ('reference test clerk', 'non_target', NULL, NULL),
    ('regional home manager', 'non_target', NULL, NULL),
    ('revenue specialist ii rops', 'non_target', NULL, NULL),
    ('seasonal piecework housekeeper - part time', 'non_target', NULL, NULL),
    ('senior manager regulatory affairs us advertising and promotion - immunology', 'non_target', NULL, NULL),
    ('senior medical courier', 'non_target', NULL, NULL),
    ('senior system safety engineer', 'non_target', NULL, NULL),
    ('sr. construction administrator - health', 'non_target', NULL, NULL),
    ('sr quality assurance engineer', 'non_target', NULL, NULL),
    ('technician fegv surface repair', 'non_target', NULL, NULL),
    ('title service representative ii', 'non_target', NULL, NULL),
    ('wind and connect 3rd shift 3045', 'non_target', NULL, NULL),
    ('technical support', 'non_target', NULL, NULL),
    ('account manager-eastern us/canada fluid management', 'non_target', NULL, NULL),
    ('accounts payable specialist', 'non_target', NULL, NULL),
    ('analyst', 'target', NULL, NULL),
    ('android engineer', 'target', NULL, NULL),
    ('benefits analyst', 'non_target', NULL, NULL),
    ('bilingual japanese/english logistics coordinator', 'non_target', NULL, NULL),
    ('brand designer', 'non_target', NULL, NULL),
    ('business operations manager', 'target', NULL, NULL),
    ('calibration technician', 'non_target', NULL, NULL),
    ('collections specialist', 'non_target', NULL, NULL),
    ('compensation analyst', 'non_target', NULL, NULL),
    ('compensation manager', 'non_target', NULL, NULL),
    ('content manager', 'non_target', NULL, NULL),
    ('customer marketing manager', 'target', NULL, NULL),
    ('customer operations specialist', 'target', NULL, NULL),
    ('customer service agent', 'target', NULL, NULL),
    ('customer support representative', 'target', NULL, NULL),
    ('data ai intern', 'target', NULL, NULL),
    ('data engineering manager', 'target', NULL, NULL),
    ('data governance analyst', 'target', NULL, NULL),
    ('data visualization architect', 'target', NULL, NULL),
    ('deal desk manager', 'non_target', NULL, NULL),
    ('engineer/sr. engineer - validation', 'target', NULL, NULL),
    ('event coordinator', 'non_target', NULL, NULL),
    ('event marketing manager', 'non_target', NULL, NULL),
    ('facilities manager', 'non_target', NULL, NULL),
    ('field access manager - northeast', 'non_target', NULL, NULL),
    ('fp a analyst', 'non_target', NULL, NULL),
    ('growth marketing manager', 'non_target', NULL, NULL),
    ('hr intern', 'non_target', NULL, NULL),
    ('incoming quality control technician', 'non_target', NULL, NULL),
    ('instrumentation and controls engineer', 'non_target', NULL, NULL),
    ('logistics manager', 'non_target', NULL, NULL),
    ('logistics specialist', 'non_target', NULL, NULL),
    ('manager platform engineering', 'non_target', NULL, NULL),
    ('marketing intern', 'target', NULL, NULL),
    ('market leader', 'non_target', NULL, NULL),
    ('material planner', 'non_target', NULL, NULL),
    ('medical science liaison - nephrology western u.s.', 'non_target', NULL, NULL),
    ('medical science liaison - transplant / infectious diseaes mid-atlantic region', 'non_target', NULL, NULL),
    ('medical science liaison - transplant / infectious diseases great plains region', 'non_target', NULL, NULL),
    ('mes engineer', 'non_target', NULL, NULL),
    ('metrology engineer', 'non_target', NULL, NULL),
    ('multicraft maintenance tech', 'non_target', NULL, NULL),
    ('network architect', 'target', NULL, NULL),
    ('new product introduction development engineer medical device', 'target', NULL, NULL),
    ('onboarding specialist', 'non_target', NULL, NULL),
    ('planner', 'non_target', NULL, NULL),
    ('procurement clerk', 'non_target', NULL, NULL),
    ('product applications engineer', 'target', NULL, NULL),
    ('qms specialist', 'non_target', NULL, NULL),
    ('quality assurance specialist - supplier quality', 'non_target', NULL, NULL),
    ('remote service engineer mri', 'non_target', NULL, NULL),
    ('revenue manager', 'non_target', NULL, NULL),
    ('revenue operations manager', 'non_target', NULL, NULL),
    ('risk manager', 'target', NULL, NULL),
    ('sales development representative japan', 'non_target', NULL, NULL),
    ('salesforce administrator', 'non_target', NULL, NULL),
    ('sales support specialist', 'non_target', NULL, NULL),
    ('scrum master', 'target', NULL, NULL),
    ('senior architect', 'non_target', NULL, NULL),
    ('senior brand designer', 'non_target', NULL, NULL),
    ('senior compensation analyst', 'non_target', NULL, NULL),
    ('senior engagement manager', 'non_target', NULL, NULL),
    ('senior facilities engineer', 'non_target', NULL, NULL),
    ('senior government affairs manager', 'non_target', NULL, NULL),
    ('senior manager engineering - cloud infrastructure', 'non_target', NULL, NULL),
    ('senior manager enterprise security', 'non_target', NULL, NULL),
    ('senior manager marketing', 'non_target', NULL, NULL),
    ('senior manager sales', 'non_target', NULL, NULL),
    ('senior manager tax', 'non_target', NULL, NULL),
    ('senior optical inspection technician', 'non_target', NULL, NULL),
    ('senior product sales mr', 'non_target', NULL, NULL),
    ('senior software architect', 'non_target', NULL, NULL),
    ('senior user experience researcher - legal data intelligence', 'non_target', NULL, NULL),
    ('senior ux designer', 'non_target', NULL, NULL),
    ('software development engineer in test', 'target', NULL, NULL),
    ('software reliability engineering team manager', 'target', NULL, NULL),
    ('sr. product designer', 'target', NULL, NULL),
    ('strategic marketing manager celgard', 'non_target', NULL, NULL),
    ('strategic sourcing manager', 'target', NULL, NULL),
    ('supplier quality manager', 'target', NULL, NULL),
    ('talent community', 'non_target', NULL, NULL),
    ('technical support specialist - evening', 'non_target', NULL, NULL),
    ('technical support specialist - weekday overnight - government', 'non_target', NULL, NULL),
    ('technical support specialist - weekend - government', 'non_target', NULL, NULL),
    ('telesales representative', 'non_target', NULL, NULL),
    ('third party risk manager', 'non_target', NULL, NULL),
    ('utility operator', 'non_target', NULL, NULL),
    ('advanced quality engineer', 'non_target', NULL, NULL),
    ('community manager', 'non_target', NULL, NULL),
    ('customer support engineer', 'target', NULL, NULL),
    ('facilities operations engineer', 'non_target', NULL, NULL),
    ('financial analyst ii', 'target', NULL, NULL),
    ('global supply chain manager', 'non_target', NULL, NULL),
    ('inventory control clerk - 2nd shift', 'non_target', NULL, NULL),
    ('inventory control specialist', 'non_target', NULL, NULL),
    ('inventory coordinator', 'non_target', NULL, NULL),
    ('lab manager', 'non_target', NULL, NULL),
    ('operation technician', 'non_target', NULL, NULL),
    ('regulatory affairs specialist', 'non_target', NULL, NULL),
    ('security architect', 'non_target', NULL, NULL),
    ('senior manager data science', 'non_target', NULL, NULL),
    ('senior manager fp a', 'non_target', NULL, NULL),
    ('senior manager software development engineering', 'non_target', NULL, NULL),
    ('senior manager strategic partnerships', 'non_target', NULL, NULL),
    ('senior sales account manager', 'non_target', NULL, NULL),
    ('senior sales development representative', 'non_target', NULL, NULL),
    ('sourcing specialist', 'non_target', NULL, NULL),
    ('sr. salesforce developer', 'non_target', NULL, NULL),
    ('test process engineer', 'target', NULL, NULL),
    ('toolmaker', 'non_target', NULL, NULL),
    ('web developer', 'target', NULL, NULL),
    ('3rd shift security guard', 'non_target', NULL, NULL),
    ('account manager - german speaking', 'non_target', NULL, NULL),
    ('administrator - admin support', 'non_target', NULL, NULL),
    ('adtj ate photo engineer', 'non_target', NULL, NULL),
    ('advanced technology japan engineer cmp process', 'non_target', NULL, NULL),
    ('advanced technology japan engineer cvd/pvd', 'non_target', NULL, NULL),
    ('advanced technology japan engineer dry etch', 'non_target', NULL, NULL),
    ('aerospace software certification engineer', 'non_target', NULL, NULL),
    ('agente de vendas - id f', 'non_target', NULL, NULL),
    ('alternant amélioration continue h/f', 'non_target', NULL, NULL),
    ('analista de desenvolvimento de software ii', 'non_target', NULL, NULL),
    ('analista de desenvolvimento de software iii', 'non_target', NULL, NULL),
    ('analista de design de produto sênior', 'non_target', NULL, NULL),
    ('analista de produtos sênior', 'non_target', NULL, NULL),
    ('application developer', 'target', NULL, NULL),
    ('assembly technician i', 'non_target', NULL, NULL),
    ('assistant project manager', 'target', NULL, NULL),
    ('associate analyst data science', 'target', NULL, NULL),
    ('associate manager core annotations', 'non_target', NULL, NULL),
    ('associate selling', 'non_target', NULL, NULL),
    ('authorization representative ii', 'non_target', NULL, NULL),
    ('beauty business manager - guerlain', 'non_target', NULL, NULL),
    ('beauty concierge', 'non_target', NULL, NULL),
    ('bim engineer', 'non_target', NULL, NULL),
    ('biomedical technician apprentice austin metro area', 'non_target', NULL, NULL),
    ('bizdev iv - crédito e plataformas de decisão', 'non_target', NULL, NULL),
    ('business continuity senior advisor information security senior advisor', 'non_target', NULL, NULL),
    ('cao designer - technician h/f', 'non_target', NULL, NULL),
    ('capital supplier mgr fe pro site ops sg', 'non_target', NULL, NULL),
    ('cash admin', 'non_target', NULL, NULL),
    ('cdi - superviseur chantier h/f', 'non_target', NULL, NULL),
    ('client due diligence specialist', 'non_target', NULL, NULL),
    ('cmp process engineer', 'non_target', NULL, NULL),
    ('cnc-dreher w/m/d', 'non_target', NULL, NULL),
    ('cnc-schleifer w/m/d', 'non_target', NULL, NULL),
    ('compliance engineer', 'non_target', NULL, NULL),
    ('computer engineer ce', 'target', NULL, NULL),
    ('contamination control and esd engineer', 'non_target', NULL, NULL),
    ('coordenador a de engenharia de software', 'non_target', NULL, NULL),
    ('cost engineer', 'non_target', NULL, NULL),
    ('customer care representative i', 'target', NULL, NULL),
    ('data and reporting analyst', 'target', NULL, NULL),
    ('data entry clerk', 'target', NULL, NULL),
    ('data management analyst', 'target', NULL, NULL),
    ('delivery manager 2 - grid orchestration software gridos', 'non_target', NULL, NULL),
    ('deputy company secretary', 'non_target', NULL, NULL),
    ('design layout engineer', 'non_target', NULL, NULL),
    ('dram process integration engineer', 'non_target', NULL, NULL),
    ('dry etch process develop engineer', 'non_target', NULL, NULL),
    ('ehs officer', 'non_target', NULL, NULL),
    ('ehs senior engineer', 'non_target', NULL, NULL),
    ('emea senior benefits partner', 'non_target', NULL, NULL),
    ('engineer - customer project engineering', 'target', NULL, NULL),
    ('engineer deg layout', 'non_target', NULL, NULL),
    ('engineer demqra automotive pqre', 'non_target', NULL, NULL),
    ('engineer - facilities ultra pure water and waste water', 'non_target', NULL, NULL),
    ('engineer fecos cpie', 'non_target', NULL, NULL),
    ('engineer hig hbm', 'non_target', NULL, NULL),
    ('engineer hig-hbm product engineering media health reliability coding', 'target', NULL, NULL),
    ('engineer hvm equip pv eq', 'non_target', NULL, NULL),
    ('engineer process and equipment engineering', 'target', NULL, NULL),
    ('engineer process integration', 'target', NULL, NULL),
    ('engineer product development engineering key equipment group pde keg', 'target', NULL, NULL),
    ('engineer real time defect analysis', 'non_target', NULL, NULL),
    ('engineer scanner equipment', 'non_target', NULL, NULL),
    ('engineer/senior ce product yield enhancement', 'non_target', NULL, NULL),
    ('engineer - systems engineering', 'target', NULL, NULL),
    ('engineer test solutions', 'target', NULL, NULL),
    ('engineer-wet process equipment development', 'non_target', NULL, NULL),
    ('environment health safety engineer - safety', 'non_target', NULL, NULL),
    ('erection commissioning engineer - gas insulated substation', 'non_target', NULL, NULL),
    ('especialista de produtos', 'non_target', NULL, NULL),
    ('especialista de sre i', 'non_target', NULL, NULL),
    ('estágio em engenharia de aplicação', 'non_target', NULL, NULL),
    ('estágio em parts services latam - fulfillment', 'non_target', NULL, NULL),
    ('euv mask beol r d engineer', 'non_target', NULL, NULL),
    ('euv mask technology r d engineer', 'non_target', NULL, NULL);

WITH proposed AS (
    SELECT manual.normalized_title,
           label.classification_status AS previous_status,
           manual.classification_status AS new_status,
           CASE WHEN manual.classification_status = 'target'
                THEN COALESCE(NULLIF(manual.canonical_role, ''), label.canonical_role)
                ELSE NULL
           END AS canonical_role,
           concat_ws('; ',
               'manual_title_review_round3_2026-06-27: workbook label=' || manual.classification_status,
               NULLIF(manual.note, '')
           ) AS decision_reason
    FROM manual_title_labels_20260627_round3 manual
    LEFT JOIN jobpush.job_title_labels label USING (normalized_title)
), changed AS (
    SELECT *
    FROM proposed
    WHERE previous_status IS DISTINCT FROM new_status
       OR NOT EXISTS (
           SELECT 1 FROM jobpush.job_title_labels existing
           WHERE existing.normalized_title = proposed.normalized_title
       )
)
INSERT INTO jobpush.job_title_label_history (
    normalized_title, previous_status, new_status, canonical_role,
    decision_reason, labeled_by
)
SELECT normalized_title, previous_status, new_status, canonical_role,
       decision_reason, 'nicole'
FROM changed;

INSERT INTO jobpush.job_title_labels (
    normalized_title, classification_status, canonical_role,
    decision_reason, rule_version, labeled_by, labeled_at, updated_at
)
SELECT manual.normalized_title,
       manual.classification_status,
       CASE WHEN manual.classification_status = 'target' THEN NULLIF(manual.canonical_role, '') ELSE NULL END,
       concat_ws('; ',
           'manual_title_review_round3_2026-06-27: workbook label=' || manual.classification_status,
           NULLIF(manual.note, '')
       ) AS decision_reason,
       'manual-title-review-round3-2026-06-27',
       'nicole',
       now(),
       now()
FROM manual_title_labels_20260627_round3 manual
ON CONFLICT (normalized_title) DO UPDATE SET
    classification_status = EXCLUDED.classification_status,
    canonical_role = EXCLUDED.canonical_role,
    decision_reason = EXCLUDED.decision_reason,
    rule_version = EXCLUDED.rule_version,
    labeled_by = EXCLUDED.labeled_by,
    labeled_at = EXCLUDED.labeled_at,
    updated_at = now();

UPDATE jobpush.job_title_ml_classifications ml
SET applied = FALSE
FROM manual_title_labels_20260627_round3 manual
WHERE ml.normalized_title = manual.normalized_title;

COMMIT;
